### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/github_issue_backup#33]
https://github.com/drdhaval2785/github_issue_backup/issues/22#issuecomment-111606354 
need for an index of issues as suggested by @funderburkjim

**Comment by gasyoun** [comment]
Endless are the features. Let's put an end?

**Comment by drdhaval2785** [comment]
Thats what the Labels are for.
Enhancement has low priority as compared to bugs.

**Comment by funderburkjim** [comment]
I agree the index.html has low priority.  System is nicely functional now.  I've yet to follow Dhaval's research on
setting up cron job in Windows; on todo list.  

Although not related to github,  the backup of Cologne sanskrit-lexicon server files to AWS  (which must be done on Cologne server) is also
functional now -- I need to improve the automation a bit, so I can do it without too much pain each month.

**Comment by gasyoun** [comment]
Now it's more about the strategy. @drdhaval2785 @gasyoun @funderburkjim should have and know where all kinds of backups are. The technology is next to perfect. It's time for human mind to step in.

**Comment by drdhaval2785** [comment]
Now each repo has index.html.

Whatever has been fetched is stored with link to local copy of the issue.
index.html shows the number of issue, title (with link to the local copy of issue).

**Comment by funderburkjim** [comment]
From comment at #22,  system looks good, and is now part of my local system.  So, we now have
three continents covered - North America, India, Asia. Should be enough.

**Comment by gasyoun** [comment]
Russia will come soon. When the wave will cover America, Asia will have temporal issues as well, so not yet safe :v:
