### ISSUE TITLE
Use timestamps to provisionally reload images

### ISSUE THREAD

**Issue by funderburkjim** [drdhaval2785/github_issue_backup#35]
The issues for sanskrit-lexicon/CORRECTIONS have a lot of images, which take a lot of time to download.

One possible solution to make this more efficient for an ongoing regime of backups might be to do a time comparison, so images would only need to be downloaded once.

This suggestion would apply if the 'home' folder for backups is kept the same from one backup session to
the next.

By changing the 'home directory' for the backup, a user could in essence 'force' a reload of all images;
but by keeping the 'home directory' the same as it was for a previous backup,  the user could make the
process more efficient by avoiding the reloading of most images.

Here's how this idea might be programmed:
-  When a downloaded issue file x.txt file is scanned for image links,  each such image link occurs in
  the text of either the issue text or of a particular issue comment;  AND, there is an 'updated_at' date
  field associated with the comment
- We may take the date of the Github image file to be this 'updated_at' date.
- Since the target location for a previously downloaded image (if any) is known, and has a time stamp,
  a comparison can be made between the 'updated_at' date of the Github image and the time stamp of the
  local image file.
- If the local image file doesn't exist, or if it exists but has a time stamp earlier than that of the Github image,
  then the image needs to be downloaded from Github.
  Otherwise, the image doesn't need to be downloaded.
- It might be that time-zones would have be taken into account when comparing Github time stamps with
  time stamps of local files.

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/github_issue_backup/commit/c0a0d96edb959701578ca2e07afe1d49827980af closed this
